### ISSUE TITLE
(Feature) Inital version of the iOS app

### ISSUE THREAD

**Issue by dusan-turajlic** [TurkuForge/baby-project-ios#3]
## Detailed Description

Create an initial version of the application with the following features

- [x] Can connect to the API endpoint
- [x] Can display all the channels the API provides
- [x] Can open and subscribe to a single channels endpoint
- [x] Can send and receive messages

## Context

So we can start testing the app and figure out if there are any obeys flaws in our architecture.

**Comment by OttoFI** [comment]
I kind of forgot about updating / following this issue, I guess we can close it now since I just merged the initial version 😄
